# travis config

language: r
sudo: false
cache: packages

warnings_are_errors: true

r:
- devel

r_github_packages:
  - berndbischl/BBmisc
  - berndbischl/ParamHelpers

before_install:
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0) install.packages("devtools")'

after_success:
  - Rscript -e 'covr::codecov(type = "tests")'

notifications:
  email:
    on_success: change
    on_failure: always
